---
version: "3.8"
services:
  gateway:
    image: ishenle/ubuntu:18.04
    container_name: gateway
    restart: on-failure
    # command: ["sleep","infinity"]
    command: ["/usr/bin/tail", "-f", "/etc/hosts"]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
    networks:
      server:
        ipv4_address: 10.0.0.100
      client:
        ipv4_address: 192.168.0.100

  server:
    image: ishenle/ubuntu:18.04
    container_name: server
    restart: on-failure
    command: ["/usr/bin/tail", "-f", "/etc/hosts"]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      server:
        ipv4_address: 10.0.0.10
    depends_on:
      - gateway

  client:
    image: ishenle/ubuntu:18.04
    container_name: client
    restart: on-failure
    command: ["/usr/bin/tail", "-f", "/etc/hosts"]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      client:
        ipv4_address: 192.168.0.10
    depends_on:
      - gateway

networks:
  front:
    driver: bridge
    enable_ipv6: false

  server:
    driver: macvlan
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.100
    driver_opts:
      macvlan_mode: bridge

  client:
    driver: macvlan
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.100
    driver_opts:
      macvlan_mode: bridge
